name: CI

on: [push]

permissions: read-all

jobs:
  test_actions:
    name: Test actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for testing preparation
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Use Node.js current version
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Build the actions
        run: npm run build

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955'
        with:
          credentials_json: ${{ secrets.FIREBASE_DEPLOYMENT_GAC }}

      - name: Test actions for simple action
        uses: ./
        with:
          project: github-workflow-sws

      - name: Test actions for monorepo
        uses: ./
        with:
          project: github-workflow-sws
          config: frontend/firebase.json

      - name: Test actions for with arguments
        uses: ./
        with:
          project: github-workflow-sws
          hosting: true
